services:
  db:
    image: postgres:16-alpine
    container_name: sportsbot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportsbot
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sportsbot"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      target: dev
    container_name: sportsbot-api
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: npm run start:dev

volumes:
  db_data: